[server]
host = "127.0.0.1"
port = 8080

[log]
level = "info"  # Available values: trace, debug, info, warn, error
directory = "logs"  # Log file directory
prefix = "app"     # Log file name prefix
max_days = 30      # Maximum days to keep logs 